### ISSUE TITLE
error parsing response from online synchronization

### ISSUE THREAD

**Issue by obilodeau** [tomboy-notes/tomdroid#53]
Hi! I've installed version 0.7.1 and when I try to sync via Ubuntu One's server it gives me error "Error parsing response from Online Synchronization".

---

Imported from Launchpad using lp2gh.
- date created: 2012-09-15T14:33:18Z
- owner: k-bx
- assignee: j-4
- the launchpad url was https://bugs.launchpad.net/bugs/1051294

**Comment by obilodeau** [comment]
(by j-4)
Hi! can you reproduce this problem or did it just occure once?
If you can reproduce i, please send us a Logcat! You can get it with this program: https://play.google.com/store/apps/details?id=org.jtb.alogcat

Thanks for your report!

**Comment by obilodeau** [comment]
(by k-bx)
Hi. Yes, it happens on different devices all the time, so it seems as issue with my notes somehow (desktop tomboy had issues on first syncs, but now it works ok).

I've installed alogcat, but it doesn't seem to produce any info (the GC_CONCURRENT one was produced during 2 launches of sync operation). Here it is:

--------- beginning of /dev/log/main
D/dalvikvm( 6699): DexOpt: 'Landroid/annotation/SuppressLint;' has an earlier definition; blocking out
D/dalvikvm( 6699): DexOpt: 'Landroid/annotation/TargetApi;' has an earlier definition; blocking out
D/dalvikvm( 6699): DexOpt: not verifying/optimizing 'Landroid/annotation/SuppressLint;': multiple definitions
D/dalvikvm( 6699): DexOpt: not verifying/optimizing 'Landroid/annotation/TargetApi;': multiple definitions
D/dalvikvm( 6699): DexOpt: load 47ms, verify+opt 189ms, 761732 bytes
I/dalvikvm( 7779): Turning on JNI app bug workarounds for target SDK version 11...
D/dalvikvm( 7779): GC_CONCURRENT freed 157K, 7% free 7498K/8007K, paused 12ms+3ms, total 35ms
W/InputEventReceiver( 7779): Attempted to finish an input event but the input event receiver has already been disposed.

**Comment by obilodeau** [comment]
(by j-4)
It might be that aLogCat is not working on Android versions > 2.3. I
also had issues with 4.1. You could try another Logcat reader from the
market. (e.g. CatLog, it requires root on 4.1).
If you have the Android SDK installed, please enable Debugging mode on
your device and connect it through USB. Then you can read out the logs
as well, either with Eclipse (plugin must be installed!) or with adb
(http://developer.android.com/tools/help/logcat.html).

Thank you for your help!

**Comment by obilodeau** [comment]
(by noahy)
I'm willing to bet this was solved in the meantime; any chance you can compile from source code?  0.7.1 is now pretty old.

Also, just fyi, there are at least two FOSS logcat viewers in the market.  As with everything,  search google play for "open source logcat".

**Comment by obilodeau** [comment]
(by j-4)
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Oh, you are using 0.7.1?
Maybe best is to wait for a few days until 0.7.2 gets released and
then try again!

You could also try this daily build from today, but you have to
reinstall the app (as it is signed with a different key):
http://goo.gl/fKg6N

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.12 (GNU/Linux)
Comment: Using GnuPG with Mozilla - http://www.enigmail.net/

iEYEARECAAYFAlBYYUoACgkQXeaPvgR0RGeiSQCgkaW5liS2TGQL0x3kew/sRJQV
a+cAn3wIq9baTSLbGnx9/7CQq3HpXW2t
=uB6H
-----END PGP SIGNATURE-----

**Comment by obilodeau** [comment]
(by k-bx)
Ok, just tried the daily build from today you pointed to -- it still has the issue. I'll then try to use other logcat tools.

**Comment by obilodeau** [comment]
(by k-bx)
Got it!

**Comment by obilodeau** [comment]
(by k-bx)
Guess I have too much notes? :)

**Comment by obilodeau** [comment]
(by j-4)
no... some people have much more notes than 350 :-)

Its a problem with the cursers, they need to be closed again somehow,
http://stackoverflow.com/questions/12029437/android-mysqlite-cursorwindowallocationexception-crash

**Comment by obilodeau** [comment]
(by j-4)
10-17 12:03:59.933: E/CursorWindow(30654): Could not allocate CursorWindow '/data/data/org.tomdroid/databases/tomdroid-notes.db' of size 2097152 due to error -12.
10-17 12:03:59.943: E/SyncService(30654): Problem syncing in thread
10-17 12:03:59.943: E/SyncService(30654): android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=682 (# cursors opened by this proc=682)
10-17 12:03:59.943: E/SyncService(30654):   at android.database.CursorWindow.<init>(CursorWindow.java:104)
10-17 12:03:59.943: E/SyncService(30654):   at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
10-17 12:03:59.943: E/SyncService(30654):   at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
10-17 12:03:59.943: E/SyncService(30654):   at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
10-17 12:03:59.943: E/SyncService(30654):   at android.content.ContentResolver.query(ContentResolver.java:388)
10-17 12:03:59.943: E/SyncService(30654):   at android.content.ContentResolver.query(ContentResolver.java:313)
10-17 12:03:59.943: E/SyncService(30654):   at org.tomdroid.NoteManager.getNoteByGuid(NoteManager.java:89)
10-17 12:03:59.943: E/SyncService(30654):   at org.tomdroid.sync.SyncService.prepareSyncableNotes(SyncService.java:230)
10-17 12:03:59.943: E/SyncService(30654):   at org.tomdroid.sync.web.SnowySyncService.access$8(SnowySyncService.java:1)
10-17 12:03:59.943: E/SyncService(30654):   at org.tomdroid.sync.web.SnowySyncService$3.run(SnowySyncService.java:261)
10-17 12:03:59.943: E/SyncService(30654):   at org.tomdroid.sync.SyncService$1.run(SyncService.java:169)
10-17 12:03:59.943: E/SyncService(30654):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
10-17 12:03:59.943: E/SyncService(30654):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
10-17 12:03:59.943: E/SyncService(30654):   at java.lang.Thread.run(Thread.java:856)

Log from Jareds Tablet with 900 notes :-)

**Comment by obilodeau** [comment]
(by j-4)
@k-bx: could you please test this build? http://goo.gl/fKg6N
it should be fixed here.

**Comment by obilodeau** [comment]
(by k-bx)
Yes, that worked like a charm! Thanks a lot!

**Comment by obilodeau** [comment]
(by rsyring)
I have the same error response.  I tried the test build above.  It downloaded some of my notes, but then errored out with the "unable to parse response" message.  In addition, when I try to sync again, now it says "sync already in progress".

**Comment by obilodeau** [comment]
(by j-4)
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Please attach a logcat. You can get it either with apps directly on
the device (aLogCat, CatLog, may rewire root) or with "adb logcat"
using the Andorid SDK and a USB cable.
Please use the test-build posted before, as only there the recursive
logs are enabled.
Thanks,
Stefan

On 10/28/2012 10:54 PM, Randy Syring wrote:

> I have the same error response.  I tried the test build above.  It 
> downloaded some of my notes, but then errored out with the "unable
> to parse response" message.  In addition, when I try to sync again,
> now it says "sync already in progress".

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.12 (GNU/Linux)
Comment: Using GnuPG with Mozilla - http://www.enigmail.net/

iEYEARECAAYFAlCOPi4ACgkQXeaPvgR0RGdrnACeKQuD9OxpPQI/YUZNIPxQzJ1o
djgAn2N679pcxpbNYJGHNZeIgy/rYxqX
=xDlS
-----END PGP SIGNATURE-----

**Comment by obilodeau** [comment]
(by rsyring)
I tried syncing Tomdroid today as the first step in trying to get some log files for you.  Interestingly enough, it worked, I no longer get the error message.

**Comment by obilodeau** [comment]
(by rsyring)
Its back :(

I installed the build in the comment above, installed alogcat, synched and produced the error, but I don't see anything in the logs regarding Tomdroid.  Can you give me more specific instructions on getting you the log files?

**Comment by obilodeau** [comment]
(by rsyring)
Turns out that my recent upgrade to Jelly Bean means that the logger apps no longer work on non-rooted phones.  I'll see about getting the Android SDK up and going so I can get the log output.  If you can point to a dead-simple tutorial on that, it would be very helpful.  Otherwise, np, it will just take some time before I can research, install, etc.

**Comment by obilodeau** [comment]
(by obilodeau)
http://developer.android.com/sdk/installing/bundle.html

Once everything is installed. If you are a CLI type of guy, plugin your android device and do:

$ adb logcat

Otherwise you can get the logcat out of DDMS (D<something> Device Manager...).

On Windows you might need a USB driver from google or your phone vendor: http://developer.android.com/sdk/win-usb.html

On OSX or linux you might need a udev entry: http://developer.android.com/tools/device.html

logcat - http://developer.android.com/tools/help/logcat.html

Might seem complicated but it's not that bad actually. Do not hesitate to ask for further indications. Cheers!

**Comment by obilodeau** [comment]
(by rsyring)
Ok, here is the log output, sorry it took so long:

12-31 17:05:03.916  8119  9172 E SyncService: Problem syncing in thread
12-31 17:05:03.916  8119  9172 E SyncService: android.util.TimeFormatException: Unexpected length; should be 33 characters
12-31 17:05:03.916  8119  9172 E SyncService:   at android.text.format.Time.nativeParse3339(Native Method)
12-31 17:05:03.916  8119  9172 E SyncService:   at android.text.format.Time.parse3339(Time.java:487)
12-31 17:05:03.916  8119  9172 E SyncService:   at org.tomdroid.Note.getLastChangeDate(Note.java:184)
12-31 17:05:03.916  8119  9172 E SyncService:   at org.tomdroid.sync.SyncService.prepareSyncableNotes(SyncService.java:330)
12-31 17:05:03.916  8119  9172 E SyncService:   at org.tomdroid.sync.web.SnowySyncService.access$8(SnowySyncService.java:1)
12-31 17:05:03.916  8119  9172 E SyncService:   at org.tomdroid.sync.web.SnowySyncService$3.run(SnowySyncService.java:263)
12-31 17:05:03.916  8119  9172 E SyncService:   at org.tomdroid.sync.SyncService$1.run(SyncService.java:169)
12-31 17:05:03.916  8119  9172 E SyncService:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
12-31 17:05:03.916  8119  9172 E SyncService:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
12-31 17:05:03.916  8119  9172 E SyncService:   at java.lang.Thread.run(Thread.java:856)

**Comment by obilodeau** [comment]
(by obilodeau)
Hi Randy, I filed your issue here: lp:1096420 (https://bugs.launchpad.net/tomdroid/+bug/1096420) since the original issue here is different and has been fixed already. Please subscribe and follow that bug. I'll have questions for you over there.
